export interface TemplateDefinition {
  id: string;
  slug?: string;
  title: string;
  description: string;
  category: "Featured";
  stars?: string;
  nodes: any[];
  edges: any[];
}

export const PRELOADED_TEMPLATES: TemplateDefinition[] = [
  {
    id: "airbnb",
    slug: "airbnb",
    title: "airbnb",
    description:
      "Global home-sharing platform serving 150M+ guests. Multi-region, search-heavy, with real-time messaging and payments.",
    category: "Featured",
    stars: "84.2k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -220, y: 220 },
        data: { label: "Guests & Hosts" },
      },
      {
        id: "n2",
        type: "cdn",
        position: { x: 0, y: 80 },
        data: { label: "CloudFront CDN" },
      },
      {
        id: "n3",
        type: "loadBalancer",
        position: { x: 220, y: 220 },
        data: { label: "ALB" },
      },
      {
        id: "n4",
        type: "microservice",
        position: { x: 420, y: 80 },
        data: { label: "Listing Service" },
      },
      {
        id: "n5",
        type: "microservice",
        position: { x: 420, y: 220 },
        data: { label: "Booking Service" },
      },
      {
        id: "n6",
        type: "microservice",
        position: { x: 420, y: 360 },
        data: { label: "Messaging Service" },
      },
      {
        id: "n7",
        type: "search",
        position: { x: 660, y: 80 },
        data: { label: "Elasticsearch" },
      },
      {
        id: "n8",
        type: "database",
        position: { x: 660, y: 220 },
        data: { label: "PostgreSQL", provider: "postgresql" },
      },
      {
        id: "n9",
        type: "cache",
        position: { x: 660, y: 360 },
        data: { label: "Redis" },
      },
      {
        id: "n10",
        type: "stripe",
        position: { x: 420, y: 500 },
        data: { label: "Stripe Payments" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n3", target: "n5" },
      { id: "e5", source: "n3", target: "n6" },
      { id: "e6", source: "n4", target: "n7" },
      { id: "e7", source: "n5", target: "n8" },
      { id: "e8", source: "n6", target: "n9" },
      { id: "e9", source: "n5", target: "n10" },
    ],
  },
  {
    id: "netflix",
    slug: "netflix",
    title: "netflix",
    description:
      "Streaming platform serving 260M+ subscribers. Microservices on AWS, Chaos Engineering, and global CDN for video delivery.",
    category: "Featured",
    stars: "212.3k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -220, y: 220 },
        data: { label: "260M Subscribers" },
      },
      {
        id: "n2",
        type: "cdn",
        position: { x: 0, y: 100 },
        data: { label: "Open Connect CDN" },
      },
      {
        id: "n3",
        type: "gateway",
        position: { x: 220, y: 220 },
        data: { label: "API Gateway (Zuul)" },
      },
      {
        id: "n4",
        type: "microservice",
        position: { x: 440, y: 60 },
        data: { label: "Recommendation" },
      },
      {
        id: "n5",
        type: "microservice",
        position: { x: 440, y: 180 },
        data: { label: "Streaming Service" },
      },
      {
        id: "n6",
        type: "microservice",
        position: { x: 440, y: 300 },
        data: { label: "Auth Service" },
      },
      {
        id: "n7",
        type: "microservice",
        position: { x: 440, y: 420 },
        data: { label: "Billing Service" },
      },
      {
        id: "n8",
        type: "database",
        position: { x: 680, y: 60 },
        data: { label: "Cassandra" },
      },
      {
        id: "n9",
        type: "storage",
        position: { x: 680, y: 180 },
        data: { label: "S3 (Video)" },
      },
      {
        id: "n10",
        type: "bus",
        position: { x: 680, y: 300 },
        data: { label: "Kafka" },
      },
      {
        id: "n11",
        type: "cache",
        position: { x: 680, y: 420 },
        data: { label: "EVCache (Redis)" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n1", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n3", target: "n5" },
      { id: "e5", source: "n3", target: "n6" },
      { id: "e6", source: "n3", target: "n7" },
      { id: "e7", source: "n4", target: "n8" },
      { id: "e8", source: "n5", target: "n9" },
      { id: "e9", source: "n5", target: "n10" },
      { id: "e10", source: "n4", target: "n11" },
    ],
  },
  {
    id: "stripe",
    slug: "stripe",
    title: "stripe",
    description:
      "Financial infrastructure for the internet. Handles billions in payments with 99.999% uptime and real-time webhooks.",
    category: "Featured",
    stars: "53.1k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -220, y: 250 },
        data: { label: "Merchants & Devs" },
      },
      {
        id: "n2",
        type: "gateway",
        position: { x: 20, y: 150 },
        data: { label: "API Gateway" },
      },
      {
        id: "n3",
        type: "waf",
        position: { x: 20, y: 320 },
        data: { label: "WAF / Fraud ML" },
      },
      {
        id: "n4",
        type: "microservice",
        position: { x: 260, y: 80 },
        data: { label: "Charge Service" },
      },
      {
        id: "n5",
        type: "microservice",
        position: { x: 260, y: 220 },
        data: { label: "Routing Engine" },
      },
      {
        id: "n6",
        type: "microservice",
        position: { x: 260, y: 360 },
        data: { label: "Webhook Delivery" },
      },
      {
        id: "n7",
        type: "database",
        position: { x: 500, y: 80 },
        data: { label: "PostgreSQL (ledger)" },
      },
      {
        id: "n8",
        type: "queue",
        position: { x: 500, y: 220 },
        data: { label: "SQS Queue" },
      },
      {
        id: "n9",
        type: "api",
        position: { x: 500, y: 360 },
        data: { label: "Card Networks (Visa/MC)" },
      },
      {
        id: "n10",
        type: "cache",
        position: { x: 500, y: 500 },
        data: { label: "Redis (idempotency)" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n1", target: "n3" },
      { id: "e3", source: "n2", target: "n4" },
      { id: "e4", source: "n2", target: "n5" },
      { id: "e5", source: "n4", target: "n7" },
      { id: "e6", source: "n5", target: "n9" },
      { id: "e7", source: "n5", target: "n8" },
      { id: "e8", source: "n8", target: "n6" },
      { id: "e9", source: "n4", target: "n10" },
    ],
  },
  {
    id: "uber",
    slug: "uber",
    title: "uber",
    description:
      "Real-time ride matching at massive scale. Geospatial indexing, sub-second dispatch, and surge pricing across 70+ countries.",
    category: "Featured",
    stars: "47.8k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -220, y: 250 },
        data: { label: "Riders & Drivers" },
      },
      {
        id: "n2",
        type: "gateway",
        position: { x: 0, y: 180 },
        data: { label: "API Gateway" },
      },
      {
        id: "n3",
        type: "microservice",
        position: { x: 230, y: 60 },
        data: { label: "Dispatch Engine" },
      },
      {
        id: "n4",
        type: "microservice",
        position: { x: 230, y: 200 },
        data: { label: "Geospatial Service" },
      },
      {
        id: "n5",
        type: "microservice",
        position: { x: 230, y: 340 },
        data: { label: "Surge Pricing ML" },
      },
      {
        id: "n6",
        type: "microservice",
        position: { x: 230, y: 480 },
        data: { label: "Trip Service" },
      },
      {
        id: "n7",
        type: "bus",
        position: { x: 480, y: 60 },
        data: { label: "Kafka (location events)" },
      },
      {
        id: "n8",
        type: "database",
        position: { x: 480, y: 200 },
        data: { label: "Schemaless (Cassandra)" },
      },
      {
        id: "n9",
        type: "cache",
        position: { x: 480, y: 340 },
        data: { label: "Redis (driver index)" },
      },
      {
        id: "n10",
        type: "worker",
        position: { x: 480, y: 480 },
        data: { label: "ETA ML Worker" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n2", target: "n4" },
      { id: "e4", source: "n2", target: "n5" },
      { id: "e5", source: "n2", target: "n6" },
      { id: "e6", source: "n3", target: "n7" },
      { id: "e7", source: "n4", target: "n9" },
      { id: "e8", source: "n6", target: "n8" },
      { id: "e9", source: "n3", target: "n10" },
    ],
  },
  {
    id: "discord",
    slug: "discord",
    title: "discord",
    description:
      "Real-time chat for 500M+ users. WebSocket-based messaging, voice/video routing, and single-server read-all message fan-out.",
    category: "Featured",
    stars: "22.4k",
    nodes: [
      {
        id: "n1",
        type: "user",
        position: { x: -220, y: 250 },
        data: { label: "500M Users" },
      },
      {
        id: "n2",
        type: "loadBalancer",
        position: { x: 0, y: 180 },
        data: { label: "ALB" },
      },
      {
        id: "n3",
        type: "microservice",
        position: { x: 240, y: 80 },
        data: { label: "Gateway (Elixir)" },
      },
      {
        id: "n4",
        type: "microservice",
        position: { x: 240, y: 220 },
        data: { label: "Message Service" },
      },
      {
        id: "n5",
        type: "microservice",
        position: { x: 240, y: 360 },
        data: { label: "Voice/Video (WebRTC)" },
      },
      {
        id: "n6",
        type: "bus",
        position: { x: 480, y: 80 },
        data: { label: "Kafka (message fan-out)" },
      },
      {
        id: "n7",
        type: "database",
        position: { x: 480, y: 220 },
        data: { label: "Cassandra (messages)" },
      },
      {
        id: "n8",
        type: "cache",
        position: { x: 480, y: 360 },
        data: { label: "Redis (presence)" },
      },
      {
        id: "n9",
        type: "storage",
        position: { x: 480, y: 500 },
        data: { label: "GCS (media)" },
      },
    ],
    edges: [
      { id: "e1", source: "n1", target: "n2" },
      { id: "e2", source: "n2", target: "n3" },
      { id: "e3", source: "n3", target: "n4" },
      { id: "e4", source: "n3", target: "n5" },
      { id: "e5", source: "n4", target: "n6" },
      { id: "e6", source: "n4", target: "n7" },
      { id: "e7", source: "n3", target: "n8" },
      { id: "e8", source: "n5", target: "n9" },
    ],
  },
  {
    id: "meshwork-studio",
    slug: "meshwork-studio",
    title: "meshwork-studio",
    description:
      "Target decoupled microservices architecture with gRPC IPC, Redis queue, and isolated PostgreSQL database clusters.",
    category: "Featured",
    nodes: [
      {
        id: "title",
        type: "annotation",
        position: { x: -100, y: -220 },
        width: 480,
        height: 70,
        data: {
          label:
            "## Meshwork Target Microservices Architecture\nProduction goal featuring isolated databases, API Gateway routing, Redis caching/queue, and gRPC communication.",
        },
      },
      {
        id: "internet",
        type: "user",
        position: { x: 120, y: -100 },
        data: { label: "Internet Clients" },
      },
      {
        id: "cloudflare",
        type: "cdn",
        position: { x: 120, y: 20 },
        style: { width: 168, height: 72 },
        data: { label: "Cloudflare (DNS/WAF/CDN)" },
      },
      {
        id: "nginx",
        type: "loadBalancer",
        position: { x: 120, y: 140 },
        style: { width: 192, height: 72 },
        data: { label: "Nginx Proxy" },
      },
      {
        id: "gateway",
        type: "gateway",
        position: { x: 120, y: 260 },
        style: { width: 192, height: 72 },
        data: { label: "API Gateway (JWT & Validation)" },
      },
      {
        id: "auth",
        type: "microservice",
        position: { x: -280, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Auth Service" },
      },
      {
        id: "workspace",
        type: "microservice",
        position: { x: -80, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Workspace Service" },
      },
      {
        id: "mosh",
        type: "microservice",
        position: { x: 120, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Jenkos Service" },
      },
      {
        id: "mcp",
        type: "microservice",
        position: { x: 320, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "MCP Service" },
      },
      {
        id: "worker",
        type: "worker",
        position: { x: 520, y: 400 },
        style: { width: 168, height: 72 },
        data: { label: "Background Worker" },
      },
      {
        id: "pg",
        type: "database",
        position: { x: -280, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "PostgreSQL\n(auth_db)" },
      },
      {
        id: "dynNodes",
        type: "database",
        position: { x: -80, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "DynamoDB\n(nodes)" },
      },
      {
        id: "dynChat",
        type: "database",
        position: { x: 120, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "DynamoDB\n(chat_history)" },
      },
      {
        id: "redis",
        type: "cache",
        position: { x: 520, y: 560 },
        style: { width: 144, height: 120 },
        data: { label: "Redis\n(cache/queue)" },
      },
      {
        id: "note",
        type: "note",
        position: { x: 200, y: 400 },
        width: 200,
        height: 130,
        data: {
          label:
            "### Service Rules\n- Comm. via gRPC\n- NEVER access other DBs\n- DBs are strictly owned by respective service",
        },
      },
    ],
    edges: [
      {
        id: "e1",
        source: "internet",
        target: "cloudflare",
        type: "step",
        animated: true,
      },
      {
        id: "e2",
        source: "cloudflare",
        target: "nginx",
        type: "step",
        animated: true,
      },
      {
        id: "e3",
        source: "nginx",
        target: "gateway",
        type: "step",
        animated: true,
      },
      {
        id: "e4",
        source: "gateway",
        target: "auth",
        type: "step",
        animated: true,
      },
      {
        id: "e5",
        source: "gateway",
        target: "workspace",
        type: "step",
        animated: true,
      },
      {
        id: "e6",
        source: "gateway",
        target: "mosh",
        type: "step",
        animated: true,
      },
      {
        id: "e7",
        source: "gateway",
        target: "mcp",
        type: "step",
        animated: true,
      },
      {
        id: "e8",
        source: "gateway",
        target: "worker",
        type: "step",
        animated: true,
      },
      { id: "e9", source: "auth", target: "pg", type: "step" },
      { id: "e10", source: "workspace", target: "dynNodes", type: "step" },
      { id: "e11", source: "mosh", target: "dynChat", type: "step" },
      { id: "e12", source: "worker", target: "redis", type: "step" },
      {
        id: "e13",
        source: "workspace",
        target: "auth",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e14",
        source: "mosh",
        target: "auth",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e15",
        source: "mcp",
        target: "auth",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e16",
        source: "mcp",
        target: "workspace",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
      {
        id: "e17",
        source: "worker",
        target: "workspace",
        type: "step",
        label: "gRPC",
        style: { strokeDasharray: "5,5" },
      },
    ],
  },
];
